# Generated by Django 5.2.4 on 2025-08-10 14:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_remove_cat_rating_remove_comment_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
